# Scarlet_Night Hyprland Palette

# Core
$background = rgba(121214ff)
$on_background = rgba(e5e5eaff)

# Surfaces
$surface = rgba(27272aff)
$surface_dim = rgba(121214ff)
$surface_container = rgba(27272aff)

# FIX: Define the variable causing the 'Red Bar' error
$surface_container_high = rgba(3f3f46ff)

# Accents (Red + Steel Gradient)
$primary = rgba(d63a4aff)
$secondary = rgba(9e9ea0ff)
$inactive_border = rgba(3f3f46ff)

# Text
$on_surface = rgba(e5e5eaff)
$on_primary = rgba(ffffffff)
