$background = rgba(050505ff)
$on_background = rgba(ffffffff)

$surface = rgba(0a0a0aff)
$surface_dim = rgba(050505ff)
$surface_bright = rgba(1a1a1aff)

$surface_container = rgba(141414ff)
$surface_container_low = rgba(101010ff)
$surface_container_high = rgba(202020ff)
$surface_container_highest = rgba(2a2a2aff)
$surface_container_lowest = rgba(000000ff)

$on_surface = rgba(ffffffff)
$on_surface_variant = rgba(ccccccff)

$primary = rgba(ffffffff)
$on_primary = rgba(000000ff)
$primary_container = rgba(333333ff)
$on_primary_container = rgba(ffffffff)
$primary_fixed = rgba(e0e0e0ff)
$primary_fixed_dim = rgba(c0c0c0ff)
$on_primary_fixed = rgba(000000ff)

$secondary = rgba(ccccccff)
$on_secondary = rgba(000000ff)
$secondary_container = rgba(222222ff)
$on_secondary_container = rgba(ccccccff)
$secondary_fixed = rgba(ccccccff)
$secondary_fixed_dim = rgba(aaaaaaff)
$on_secondary_fixed = rgba(000000ff)

$tertiary = rgba(808080ff)
$on_tertiary = rgba(ffffffff)
$tertiary_container = rgba(111111ff)
$on_tertiary_container = rgba(a0a0a0ff)

$error = rgba(ff5555ff)
$on_error = rgba(000000ff)
$error_container = rgba(93000aff)
$on_error_container = rgba(ffdad6ff)

$outline = rgba(444444ff)
$outline_variant = rgba(222222ff)
$shadow = rgba(000000ff)
$scrim = rgba(000000ff)
$inverse_surface = rgba(ffffffff)
$inverse_on_surface = rgba(000000ff)
$inverse_primary = rgba(000000ff)
