# Core Colors
background            #0f1417
foreground            #dfe3e7

cursor                #dfe3e7
cursor_text_color     #0f1417

selection_background  #91cef4
selection_foreground  #00344a

url_color             #91cef4

# Window borders (if you turn them back on)
active_border_color   #91cef4
inactive_border_color #8b9297
bell_border_color     #ffb4ab

# Tab bar (if you use tabs)
active_tab_foreground   #00344a
active_tab_background   #91cef4
inactive_tab_foreground #c1c7ce
inactive_tab_background #1c2024

# --- TERMINAL PALETTE ---

# Black: Surface Containers (Background variations)
color0  #262b2e
color8  #313539

# Red: Error colors
color1  #ffb4ab
color9  #93000a

# Green: Secondary (Usually a complementary soft color)
color2  #b6c9d8
color10 #374955

# Yellow: Tertiary (The "fun" accent)
color3  #cbc1e9
color11 #494263

# Blue: Primary (The main character of your wallpaper)
color4  #91cef4
color12 #004c6a

# Magenta: Mixed/Variant
color5  #c5e7ff
color13 #91cef4

# Cyan: Secondary Variant
color6  #d2e5f4
color14 #b6c9d8

# White: Text Colors
color7  #dfe3e7
color15 #c1c7ce
