################
### MONITORS ###
################

# Dual Monitor Mode (Laptop + HDMI)
monitor=HDMI-A-1,1920x1080@120.0,1600x0,1.0,bitdepth,10
monitor=eDP-1,2560x1600@165.0,0x80,1.67

# Dual monitor setup, dgpu — odd workspaces on laptop, even on HDMI
workspace=1,monitor:eDP-1,default:true
workspace=2,monitor:HDMI-A-1,default:true
workspace=3,monitor:eDP-1
workspace=4,monitor:HDMI-A-1
workspace=5,monitor:eDP-1
workspace=6,monitor:HDMI-A-1
workspace=7,monitor:eDP-1
workspace=8,monitor:HDMI-A-1
workspace=9,monitor:eDP-1
workspace=10,monitor:HDMI-A-1

# For HDR
# Syntax: monitor = NAME, RESOLUTION@HZ, POS, SCALE, bitdepth, 10, cm, hdr, sdrbrightness, 1.2
# monitor =, highres@highrr, auto, 1.25, bitdepth, 10, cm, hdr, sdrbrightness, 1.5
