# Core Colors
background            #050505
foreground            #FFFFFF
cursor                #FF2A2A
cursor_text_color     #000000
selection_background  #AA0000
selection_foreground  #ffffff
url_color             #FF2A2A

# Window borders
active_border_color   #FF2A2A
inactive_border_color #333333
bell_border_color     #FF2A2A

# Tab bar
active_tab_foreground   #000000
active_tab_background   #FF2A2A
inactive_tab_foreground #888888
inactive_tab_background #0a0a0a

# Colors
color0  #101010
color8  #303030
color1  #FF2A2A
color9  #FF2A2A
color2  #a0a0a0
color10 #c0c0c0
color3  #808080
color11 #909090
color4  #cccccc
color12 #e0e0e0
color5  #bbbbbb
color13 #dddddd
color6  #eeeeee
color14 #ffffff
color7  #f0f0f0
color15 #ffffff
